version: '3.8'

services:
  # React Frontend
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      target: builder
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - REACT_APP_API_URL=http://localhost:5000/api
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - api
    networks:
      - home-hub-network

  # Express API Backend
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=development
      - PORT=5000
      - MONGODB_URI=mongodb://mongodb:27017/homehub
      - JWT_SECRET=your-jwt-secret
    volumes:
      - ./api:/app
      - /app/node_modules
    depends_on:
      - mongodb
    networks:
      - home-hub-network

  # MongoDB Database
  mongodb:
    image: mongo:5.0
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_DATABASE=homehub
    volumes:
      - mongodb_data:/data/db
    networks:
      - home-hub-network

  # Redis Cache
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - home-hub-network

  # Nginx Reverse Proxy
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./ssl:/etc/nginx/ssl
    depends_on:
      - frontend
      - api
    networks:
      - home-hub-network

volumes:
  mongodb_data:
  redis_data:

networks:
  home-hub-network:
    driver: bridge




