name: ESLint
on: 
  push:
    branches: [ main, production, main2, production-backup ]
  pull_request:
    branches: [ main, production, main2, production-backup ]

jobs:
  lint:
    runs-on: ubuntu-latest
    name: ESLint Check
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Run ESLint
        run: npm run lint
        
      - name: Check for linting errors
        run: |
          if [ $? -ne 0 ]; then
            echo "ESLint found errors. Please fix them before merging."
            exit 1
          fi
